In [ ]:
#Blen Teshome, Lina Abdo, Sanjeev Jariwala, Dua Kheiry
#INST126
#12/12/2017
#Data cleaning mechanism

import pandas as pd

In [ ]:
df = pd.read_csv("Mapping_Inequality.csv")
df

In [ ]:
#Lina Abdo
#year_low
#change all years to 4 digits
#remove apostrophes
#remove spaces between dashes
#replace empty cells with N/A

for year in df["year_low"]:
    year = str(year)
    if len(year) == 2:
        print("19" + year)
    elif len(year) == 4:
        print(year)
    elif (" - ") in year:
        if len(year) == 9:
            year = year.replace(" - ", "-19")
            print(year)
        else:
            year = year.replace(" - '", "-19")
            print("19" + year)
    elif ("-") in year:
        if len(year) == 5:
            year = year.replace("-", "-19")
            print("19" + year)
        elif len(year) == 6:
            year = year.replace("-'", "-19")
            print("19" + year)
        elif len(year) == 7:
            year = year.replace("-", "-19")
            print(year)
        else:
            print(year)
    else:
        print("N/A")

In [ ]:
#Lina Abdo
#SV_range_low
#remove commas
#replace to with -
#remove extra symbols (%, '', .)
#add $ before numbers
#replace empty cells with N/A

for number in df["SV_range_low"]:
    number = str(number)
    number = number.replace(" to ", "-").replace(" - ", "-").replace("- ", "-")
    number = number.replace(",", "").strip("''").strip("%")
    if number.startswith("11000"):
        print("$11000")
    elif (".") in number:
        print("$9000")
    elif ("&") in number:
        print("$" + number)
    elif len(number) == 4:
        print("$" + number)
    elif ("-") in number:
        if ("-$") in number:
            print(number)
        else:
            number = number.replace("-", "-$")
            print("$" + number)
    else:
        print("N/A")

In [ ]:
#Lina Abdo
#SV_%_low
#add % after numbers
#remove extra numbers
#edit certain values
#replace empty cells with N/A

for number in df["SV_%_low"]:
    number = str(number)
    if ("nan") in number:
        print("N/A")
    elif number == "6200%":
        print("62%")
    elif "a" in number:
        print("70% (a)")
    elif ("%") in number:
        print(number)
    else:
        print(number + "%")

In [ ]:
#Lina Abdo
#RV_range_low
#replace to with -
#remove $
#capitalize first letter in words
#replace empty cells with N/A

for value in df["RV_range_low"].str.title():
    value = str(value)
    value = value.replace(" To ", "-").replace(" to ", "-").replace(" - ", "-").strip("$")
    if ("nan") in value:
        print("N/A")
    elif value == "Very Few Rental Units":
        print("Very Few Rentals")
    elif value == "Few Rental":
        print(value + "s")
    elif value == "Few":
        print(value + " Rentals")
    else:
        print(value)

In [ ]:
#Lina Abdo
#RV_predom_low
#add % after numbers
#edit values
#capitalize first letter in words
#replace empty cells with N/A

for value in df["RV_predom_low"].str.title():
    value = str(value).strip("%")
    if ("nan") in value:
        print ("N/A")
    elif value.isnumeric():
        print(value + "%")
    elif value == "27.5 (A)":
        print("27.5% (a)")
    elif (".") in value:
        print(value + "%")
    else:
        print(value)

In [ ]:
#Lina Abdo
#RV_%_low
#add % after numbers
#capitalize first letter in words
#change certain values
#add words to make consistent
#replace empty cells with N/A

for number in df["RV_%_low"].str.title(): 
    number = str(number).strip("%")
    if ("nan") in number:
        print("N/A")
    elif number.startswith("Not"):
        print(number)
    elif number == "69 (A)":
        print("69% (A)")
    elif number == "62-1/2":
        print("62.5%")
    else:
        print(number + "%")

In [ ]:
#Lina Abdo
#year_current
#change September to 09"
#change July to 07
#made years 4 digits
#replace empty cells with N/A

for year in df["year_current"]:
    year = str(year).replace("Sept. '", "09/19").replace("Sept '", "09/19")
    year = year.replace("Sept, ", "09/").replace("Sept. ", "09/")
    if "09" in year:
        print(year)
    elif year.startswith("July "):
        year = year.replace("July ", "07/")
        print(year)
    elif year.isnumeric():
        print(year)
    elif year == "Sept 1937":
        print("09/1937")
    else:
        print("N/A")

In [ ]:
#Blen Teshome
#INST126
#12/11/17
#SV_range_current
#Got rid of the unnecessary ' ' and ,
#Replaced the double spaces with single spaces
#Changed nan to N/A
#Added $ to each number
#Replaced to with -$

for number in df["SV_range_current"]:
    number = str(number)
    number = number.replace(",", "").strip("''")
    number = number.replace(" ", "")
    if "nan" in number:
        print("N/A")
    elif "12500-" in number:
        number = number.replace("-", "")
        print("$" + number)
    elif "&up" in number:
        number = number.replace("&up", " & up")
        print(number)
    elif  "$" in number:
        number = number.replace("-", "-$")
        print(number)
    elif "to" in number:
        number = number.replace("to", "-$")
        print("$" + number)
    elif "-$" not in number:
        number = number.replace("-", "-$").replace(" - ", "-$")
        print("$" + number)
    else:
        print(number)

In [ ]:
#Blen Teshome
#INST126
#12/11/17
#SV_predom_current 
#Print out everything in column
#Used .isdigit() from https://docs.python.org/3/library/stdtypes.html to print out all the numbers
#Made everything else N/A

for number in df["SV_predom_current"]:
    number = str(number)
    number = number.replace(",", "")
    if "M" in number:
        print(number)
    elif number.isdigit():
        print(number)
    elif "NA" in number:
        print("N/A")
    else:
        print("N/A")

In [ ]:
#Blen Teshome
#INST126
#12/11/17
#SV_%_current
#Added % to ever cell
#Made everything that isn't a number write out N/A

for number in df["SV_%_current"]:
    number = str(number)
    if "%" in number:
        print(number)
    elif "nan" in number:
        print("N/A")
    elif "%" not in number:
        number = str(number) + "%"
        print(number)

In [ ]:
#Blen Teshome
#INST126
#12/11/17
#RV_range_current
#Made the first letter of very and rental capital
#Changed all dashes to "to"
#Tried to get rid of the extra spaces in between the words or numbers
#If line was empty I printed N/A

for value in df["RV_range_current"]:
    value = str(value)
    if "very" in value:
        value = value.title()
        print(value)
    elif value.startswith("rental"):
        value = value.title()
        print(value)
    elif value.startswith("Owner"):
        print(value)
    elif value.startswith("Only"):
        print(value)
    elif "$" in value:
        value = value.replace("$", "")
        value = value.replace("-", " to ")
        value = value.replace(" - ", "to")
        print(value)
    elif "to" in value:
        print(value)
    elif "--" in value:
        value = value.replace("--", " to ")
        print(value)
    elif " - " in value:
        value = value.replace(" - ", " to ")
        print(value)
    elif "-" in value:
        value = value.replace("-", " to ")
        value = value.replace("-", "to")
        print(value)
    elif " to " in value:
        value = value.replace(" to ", "to")
        print(value)
    else:
        print("N/A")

In [ ]:
#Blen Teshome
#INST126
#12/11/17
#RV_predom_current
#Changed everything that wasnt a number to N/A
#For example, na to N/A

for number in df["RV_predom_current"]:
    number = str(number)
    if "NA" in number:
        print("N/A")
    elif "na" in number:
        print("N/A")
    elif " " in number:
        print("N/A")
    else:
        print(number)

In [ ]:
#Blen Teshome
#INST126
#12/11/17
#If numbers had a % I just printed the number
#If they didn't have a % I appended it to the end of the number
#Replaced nan and na with N/A to match the other cells

for number in df["RV_%_current"]:
    number = str(number)
    if "%" in number:
        print(number)
    elif "nan" in number or "na" in number:
        print("N/A")
    elif "%" not in number:
        number = number + "%"
        print(number)

In [ ]:
#Blen Teshome
#INST126
#12/11/17
#Peak_Sale
#Changed the format of the years to make it all the same
#For example, make them all 19XX or 19XX-19XX instead of XX-'XX or 19XX-XX
#Also got rid of the one random "192900.00%"
#Made all NA's change to N/A to match the previous cells
#Used the length of the numbers to be able to fix certain problems for certain numbers

for year in df["Peak_Sale"]:
    year = str(year)
    if "NA" in year:
        year = year.replace("NA", "N/A")
        print(year)
    elif len(year) == 2:
        print("19" + year)
    elif len(year) == 4:
        print(year)
    elif len(year) == 5:
        year = year.replace("28-29", "1928-1929")
        print(year)
    elif len(year) == 6:
        year = year.replace("'29", "1929")
        print("19" + year)
    elif len(year) == 7:
        year = year.replace("-28", "-1928")
        print(year)
    elif len(year) == 9:
        print(year)
    elif len(year) == 10:
        print("1929")
    else:
        print("N/A")

In [ ]:
#Blen Teshome
#INST126
#12/11/17
#Added percent sign to the digits that didn't have it already
#15000% had extra zeros so I had to single it out and print 150%
#Added N/A if blank or NA

for number in df["Peak_Sale%"]:
    number = str(number)
    if "15000%" in number:
        print("150%")
    elif "%" not in number and any(number.isdigit() for line in df["Peak_Sale%"]):
        number = number + "%"
        print(number)
    elif "%" in number:
        print(number)
    else:
        print("N/A")

In [ ]:
#Sanjeev Jariwala
#INST126
#12/11/17
#Peak_Rental_%
#adding percentages to all numbers without a % sign 
#any blank cells or confusing data without context was labeled as N/A

for number in df["Peak_Rental_%"]:
    number = str(number)
    if "nan" in number:
        print("N/A")
    elif "-" in number:
        print("N/A")
    elif "%" not in number:
        print(number + "%")
    elif "%" in number:
        print(number)

In [ ]:
#Sanjeev Jariwala
#INST126
#12/11/17
#occup_dwell
#adding percentages to all numbers without a % sign 
#any blank cells or confusing data without context was labeled as N/A

for number in df["occup_dwell"]:
    number = str(number)
    if "nan" in number:
        print("N/A")
    elif "%" not in number:
        print(number + "%")
    elif "%" in number:
        print(number)

In [ ]:
#Sanjeev Jariwala
#INST126
#12/11/17
#occup_Land 
#adding percentages to all numbers without a % sign 
#any blank cells or confusing data without context was labeled as N/A

for number in df["occup_Land"]:
    number = str(number)
    if "nan" in number:
        print("N/A")
    elif "%" not in number:
        print(number + "%")
    elif "%" in number:
        print(number)

In [ ]:
#Sanjeev Jariwala
#INST126
#12/11/17
#occup_home 
#adding percentages to all numbers without a % sign 
#Simplifying "over 90" to just >90% for efficiency 
#any blank cells or confusing data without context was labeled as N/A

for number in df["occup_home"]:
    number = str(number)
    if "nan" in number:
        print("N/A")
    elif "over" in number or "Over" in number: #simplifying over 90/Over 90 to >90%
        number = number.replace("over 90", ">90%").replace("Over 90", ">90%")
        print(number)
    elif "%" not in number:
        print(number + "%")
    elif "%" in number:
        print(number)

In [ ]:
#Sanjeev Jariwala
#INST126
#12/11/17
#Peak_Rental
#Making all years 4 digits 
#singled out towards the end because that was the only year with a format issue 
#any blank cells or confusing data without context was labeled as N/A 

for year in df["Peak_Rental"]:
    year = str(year)
    if "'" in year:
        year = year.replace("'", "19")
        print("19" + year)
    elif len(year) == 4:
        print(year)
    elif len(year) == 9:
        print(year)
    elif len(year) == 7:
        year = year.replace("-", "-19")
        print(year)
    elif len(year) == 5:
        year = year.replace("-", "-19")
        year = year.replace("26", "1926")
        print(year)
    else:
        print("N/A")

In [ ]:
#Sanjeev Jariwala
#INST126
#12/11/17
#sales_a
#grouped similar words together into a list
#broke all data into 3 categories (Poor, Fair, Good)
#Matched lists to its relative category and into a new column updatedsales_a
#All other remaining data would become N/A

new_table = ["Almost none", "Poor", "poor", "slow", "Slow", "slight", "No"]
df.loc[df.sales_a.isin(new_table), "updatedsales_a"] = "Poor"

new_table = ["Fair", "fair", "limited"]
df.loc[df.sales_a.isin(new_table), "updatedsales_a"] = "Fair"

new_table = ["Good", "good", "Yes", "Very Good", "Excellent"]
df.loc[df.sales_a.isin(new_table), "updatedsales_a"] = "Good"

for value in df["updatedsales_a"]:
    if value == "Poor":
        print("Poor")
    elif value == "Fair":
        print("Fair")
    elif value == "Good":
        print("Good")
    else:
        print("N/A")

In [ ]:
#Sanjeev Jariwala
#INST126
#12/11/17
#sales_b
#singled out specific factors that prevented consistency within column 
#altered them so that they were in the same format as the clean cells within column 
#any data without any context (just prices) would be put as N/A

for value in df["sales_b"]:
    value = str(value)
    if "sgls" in value or "Sgls" in value:
        value = value.replace("sgls", "Singles")
        value = value.replace("Sgls", "Singles")
        print(value)
    if "s  $" in value:
        value = value.replace("s  $", "s $")
        print(value)
    elif "single 5000" in value:
        value = value.replace("single 5000", "Singles $5000")
        print(value)
    elif "sty" in value:
        value = value.replace("sty", "story")
        print(value)
    elif "@" in value or "at" in value or "about" in value or "upto" in value:
        value = value.replace(" @", "")
        value = value.replace(" at", "")
        value = value.replace(" about", "")
        value = value.replace("upto", "up to")
        print(value)
    elif "1 family," in value:
        value = value.replace("1 family,", "Single family")
        print(value)
    elif "nan" in value or "None for sale" in value or "Limited number offered" in value:
        value = value.replace("nan", "N/A")
        value = value.replace("None for sale", "N/A")
        value = value.replace("Limited number offered", "N/A")
        print(value)
    elif "Singles -" in value or "Singles," in value:
        value = value.replace("Singles -", "Singles")
        value = value.replace("Singles,", "Singles")
        print(value)
    elif len(value) < 10:
        value = value.replace(value, "N/A")
        print(value)
    elif "7,500 - $8,000" in value:
        value = value.replace("7,500 - $8,000", "N/A")
        print(value)
    else:
        print(value)

In [ ]:
#Sanjeev Jariwala
#INST126
#12/11/17
#sales_c 
#grouped similar words together into a list
#broke all data into 3 categories (Poor, Fair, Good)
#Matched lists to its relative category and into a new column updatedsales_c
#All other remaining data would become N/A 

new_table = ["Almost none", "Poor", "poor", "slow", "Slow", "slight", "Very slight", "No"]
df.loc[df.sales_c.isin(new_table), "updatedsales_c"] = "Poor"

new_table = ["Fair", "fair", "limited", "Fair but increasing", "Fair but improving", "Fair improving", 
             "Fair - improving", "Fair-Improving"]
df.loc[df.sales_c.isin(new_table), "updatedsales_c"] = "Fair"

new_table = ["Good", "good", "Yes", "Very Good", "Excellent"]
df.loc[df.sales_c.isin(new_table), "updatedsales_c"] = "Good"

for value in df["updatedsales_c"]:
    if value == "Poor":
        print("Poor")
    elif value == "Fair":
        print("Fair")
    elif value == "Good":
        print("Good")
    else:
        print("N/A")

In [ ]:
#Dua Kheiry
#rental_a
#looks for inconsistent wording
#changes specific words in each "find_me" list to "Good", "Not a Rental Area", "Poor", or "N/A"

find_me = ["Practically no rentals in this area","Not rental area","OWNER AREA","Owner Area","owner company"] 
df.loc[df.rental_a.isin(find_me),"new_rental_a"] = "Not a rental area"

find_me = ["Good","good","Very good","Best","Yes"]
df.loc[df.rental_a.isin(find_me),"new_rental_a"] = "Good" 

for value in df.new_rental_a:
    if value == "Not a rental area":
        print("Not a rental area")
    elif value == "Poor":
        print("Poor")
    elif value == "Good":
        print("Good")
    else:
        print("N/A")

In [ ]:
#Dua Kheiry
#rental_b
#remove quotation marks
#Remove @ sign
#remove parantheses
#remove any excess punctuation
#remove any excess wording 
#capatalize beginning letters
#Availble statements stay the same
#correct spelling (ex. tenements, sgls, mo, M, par)
#add doller signs
#make all numbers cohesive
#spell out rm
#make all N/A cohesive
#add units to few units available
#open will be up to
#fix number(20, 25) without $
#fix single 40 to singles $40
#fix duplicates

for value in df["rental_b"]:
    value = str(value)
    value = value.strip(' " " ')
    value = value.strip(" ( ")
    value = value.strip(")")
    value = value.replace("(14 ", "14 ")
    value = value.replace(" @ ", " ")
    value = value.replace(" at ", " ")
    value = value.title()
    value = value.replace("Sgls", "Singles")
    value = value.replace("-Rm", " Room")
    value = value.replace("Rm", "Room")
    value = value.replace("3-", "3 to")
    value = value.replace(" - ", "-$")
    value = value.replace("-", "-$")
    value = value.replace("-$$", "-$")
    value = value.replace(" To 60", "-$60")
    if "Par M" in value:
        value = value.replace("Par M", "Per Month /")
        #print(line)
    if "Per Mo." in value:
        value = value.replace("Per Mo.", "Per Month /")
        #print(line)
    if value == "20":
        value = value.replace("20", "$20")
        print(value)
    if value == "25":
        value = value.replace("25", "$25")
        print(value)
    if value == "Single 40":
        value = value.replace("Single 40", "Singles $40")
        print(value)
    elif value == "Limited No. Of Units":
        value = value.replace("Limited No. Of Units", "Few Units Available")
        print(value)
    elif "Nan" in value:
        value = value.replace("Nan", "N/A")
        print(value)
    elif "Na" in value:
        value = value.replace("Na", "N/A")
        print(value)
    else:
        print(value)

In [ ]:
#Dua Kheiry
#rental_c
#looks for inconsistent wording
#changes specific words in each "find_me" list to "Good", "Poor", "Fair", or "N/A"

find_me = ["Poor","poor","Very slight","Slight"]
df.loc[df.rental_c.isin(find_me),"rental_c_2"] = "Poor"

find_me = ["Fair","fair","limited"]
df.loc[df.rental_c.isin(find_me),"rental_c_2"] = "Fair"

find_me = ["Good","good","Very good",]
df.loc[df.rental_c.isin(find_me),"rental_c_2"] = "Good"

for value in df.rental_c_2:
    if value == "Poor":
        print("Poor")
    elif value == "Fair":
        print("Fair")
    elif value == "Good":
        print("Good")
    else:
        print("N/A")

In [ ]:
#Dua Kheiry
#const_types
#createcode
#capatalize all letters
#Fix spelling (Small, -story, -room, singles,  )
#add $ 
#remove excess punctuation like -
#Change NA to N/A
#make consistent wording (few, very little etc)

for value in df["const_types"]:
    value = str(value)
    value = value.title()
    value = value.replace("Samll", "Small")
    value = value.replace("Sinlges", "Singles")
    value = value.replace("Sinngles", "Singles")
    value = value.replace("2-Sty", "2-Story")
    value = value.replace("&", "And")
    value = value.replace("4,500", "$4500")
    value = value.replace("4800", "$4800")
    value = value.replace("10,000", "$10000").replace ("$$10000", "$10000")
    value = value.replace("7,500-12,500", "$7500-$12500")
    value = value.replace("-Rm", "-Room")
    value = value.replace("Bungaloes", "Bungaloes;")
    value = value.replace(" - ", "-")
    if "$" in value:
        value= value.replace(",", "")
        print(value)
    elif value == "No":
        value = value.replace("No", "None")
        print(value)
    elif value == "Nan":
        value = value.replace("Nan", "N/A")
        print(value)
    else:
        print(value)

In [ ]:
#Dua Kheiry
#const_amount
#createcode
#add $
#change spelled out numbers to actual numbers
#make words consistent
#fix spelling (units)
#capatalize letters

for value in df["const_amount"]:
    value = str(value)
    value = value.title()
    value = value.replace(":", ",")
    value = value.replace("Good", "Good;")
    value = value.replace("40,000", "$40,000")
    value = value.replace ("$$40,000", "$40,000")
    value = value.replace("100,000", "$100,000")
    value = value.replace("One", "1")
    value = value.replace("To", "-")
    value = value.replace(" - ", "-")
    value = value.replace("Unit", "Units").replace("Unitss", "Units")
    if "No" == value:
        print("None")
    if "Nan" in value:
        value = value.replace("Nan", "N/A")
    print(value)

In [ ]:
#Dua Kheiry
#home_pur
#looks for inconsistent wording in each line
#changes specific words in each "find_me" list to "Ample", "Restricted", "None", or "N/A"

find_me = ["Ample","Good","ample","Yes","yes","good"]
df.loc[df.home_pur.isin(find_me),"home_pur_2"] = "Ample"

find_me = ["Fair","fair","limited","50%","Ample (a)","Ample (b)","Limited (a)","Limited (b)"
               "Ample on restricted basis","below","ample for home owners only","Yes-FHA","Yes FHA"]
df.loc[df.home_pur.isin(find_me),"home_pur_2"] = "Restricted"

find_me = ["No","None","none"]
df.loc[df.home_pur.isin(find_me),"home_pur_2"] = "None"

for value in df.home_pur_2:
    if value == "Ample":
        print("Ample")
    elif value == "Restricted":
        print("Restricted")
    elif value == "None":
        print("None")
    else:
        print("N/A")

In [ ]:
#Dua Kheiry
#home_build
#looks for inconsistent wording
#changes specific words in each "find_me" list to "Ample", "Restricted", "None", or "N/A"

find_me = ["Ample","Good","ample","Yes","yes","good"]
df.ix[df.home_build.isin(find_me),"new_home_build"] = "Ample"

find_me = ["Fair","fair","limited","50%","Ample (a)","Ample (b)","Limited (a)","Limited (b)"
               "Ample on restricted basis","below","ample for home owners only","Yes-FHA","Yes FHA"]
df.ix[df.home_build.isin(find_me),"new_home_build"] = "Restricted"

find_me = ["No","None","none"]
df.ix[df.home_build.isin(find_me),"new_home_build"] = "None"

for value in df.new_home_build:
    if value == "Ample":
        print("Ample")
    elif value == "Restricted":
        print("Restricted")
    elif value == "None":
        print("None")
    else:
        print("N/A")

In [ ]:
#Dua Kheiry
#Ten_fifteen_desirability
#create code
#change spelling (desirable)
#get rid of excess punctuation (.)
#change consistent wording (upward, will hold up well, N/A) 

for value in df["Ten_Fifteen_Desirability"]:
    value = str(value)
    value = value.title()
    value = value.replace('"Red"', 'Red')
    value = value.replace(".", "")
    if value == 'Still Desireable':
        value = value.replace("Still Desireable", "Still Desirable")
        print(value)
    elif value == "Nan":
        value = value.replace("Nan", "N/A")
        print(value)
    elif value == "Declining, And Probably Should Be In Red, Except That It Is New Mortgage Money Is":
        value = value. replace("Declining, And Probably Should Be In Red, Except That It Is New Mortgage Money Is", "New But Declining")            
    print(value)

In [ ]:
#Dua Kheiry
#Date
#changes each date into a string
#replaces all the single quotation marks into dashes
#replaces each month with it's numerical equivalent
#changes different formatting of date
#replaces # and empty cells into N/A

for date in df["Date"]:
    date = str(date)
    if "'" in date: #this statement doesn't work
        date = date.replace("'", "-")
        print(date)
    elif date.startswith("October"):
        date = date.replace("October 15th 1937", "10-15-1937")
        print(date)
    elif date.startswith("June"):
        date = date.replace("June 12 1937", "06-12-1937")
        print(date)
    elif "May" in date:
        date = date.replace ("3-May-37", "05-03-1937")
        date = date.replace ("4-May-37", "05-04-1937")
        date = date.replace ("5-May-37", "05-05-1937")
        print(date)
    elif date.startswith("August"):
        date = date.replace ("August 13, 1937", "08-13-1937")
        print(date)
    elif "#" in date:
        print("N/A")
    elif "July 1937" in date:
        date = date.replace("July 1937", "07/1937")
        print(date)
    elif "37" in date:
        date = date.replace("37", "1937")
        print(date)
    elif "nan" in date:
        print("N/A") 
    else: 
        print(date)